from astraauth_core.repositories.authorization import (
    InMemoryRoleAssignmentRepository,
    InMemoryRoleRepository,
    RoleAssignmentRepository,
    RoleRepository,
)
from astraauth_core.repositories.mfa import (
    BaseEmailOTPCodeRepository,
    BaseEmailOTPFactorRepository,
    BaseMFAChallengeRepository,
    BaseTOTPFactorRepository,
    EmailOTPCodeRepository,
    EmailOTPFactorRepository,
    InMemoryEmailOTPCodeRepository,
    InMemoryEmailOTPFactorRepository,
    InMemoryMFAChallengeRepository,
    InMemoryTOTPFactorRepository,
    MFAChallengeRepository,
    TOTPFactorRepository,
)
from astraauth_core.repositories.oauth import (
    AuthorizationCodeRepository,
    InMemoryAuthorizationCodeRepository,
    InMemoryOAuthClientRepository,
    InMemorySubjectRepository,
    OAuthClientRepository,
    SubjectRepository,
)
from astraauth_core.repositories.plugins import (
    InMemoryTenantPluginRegistryRepository,
    SQLTenantPluginRegistryRepository,
    TenantPluginRegistryRepository,
)
from astraauth_core.repositories.sessions import (
    BaseSessionRepository,
    InMemorySessionRepository,
    RedisSessionRepository,
    SessionRepository,
    SQLSessionRepository,
)

__all__ = [
    "AuthorizationCodeRepository",
    "OAuthClientRepository",
    "SubjectRepository",
    "InMemoryAuthorizationCodeRepository",
    "InMemoryOAuthClientRepository",
    "InMemorySubjectRepository",
    "SessionRepository",
    "BaseSessionRepository",
    "InMemorySessionRepository",
    "SQLSessionRepository",
    "RedisSessionRepository",
    "MFAChallengeRepository",
    "BaseMFAChallengeRepository",
    "InMemoryMFAChallengeRepository",
    "TOTPFactorRepository",
    "BaseTOTPFactorRepository",
    "InMemoryTOTPFactorRepository",
    "EmailOTPFactorRepository",
    "BaseEmailOTPFactorRepository",
    "InMemoryEmailOTPFactorRepository",
    "EmailOTPCodeRepository",
    "BaseEmailOTPCodeRepository",
    "InMemoryEmailOTPCodeRepository",
    "RoleRepository",
    "RoleAssignmentRepository",
    "InMemoryRoleRepository",
    "InMemoryRoleAssignmentRepository",
    "TenantPluginRegistryRepository",
    "InMemoryTenantPluginRegistryRepository",
    "SQLTenantPluginRegistryRepository",
]
