from __future__ import annotations

from typing import Protocol

from astraauth_core.adapters.http_types import HttpResponse, RequestContext


class OAuthAdapter(Protocol):
    def handle_authorize(self, req: RequestContext) -> HttpResponse: ...
    def handle_token(self, req: RequestContext) -> HttpResponse: ...
    def handle_oidc_login_start(self, req: RequestContext) -> HttpResponse: ...
    def handle_oidc_callback(self, req: RequestContext) -> HttpResponse: ...
    def handle_logout(self, req: RequestContext) -> HttpResponse: ...
    def handle_introspect(self, req: RequestContext) -> HttpResponse: ...
    def handle_jwks(self, req: RequestContext) -> HttpResponse: ...
    def handle_openid_configuration(self, *, issuer: str) -> HttpResponse: ...
